name: Automatic Version Bump, Publish and Release
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important: This will fetch all tags as well as commits

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Bump version, Publish and Release
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          VERSION_BUMP=""
          if [[ $PR_TITLE == "Deploy[Major]" ]]
          then
            VERSION_BUMP="major"
          elif [[ $PR_TITLE == "Deploy[Minor]" ]]
          then
            VERSION_BUMP="minor"
          elif [[ $PR_TITLE == "Deploy[Patch]" ]]
          then
            VERSION_BUMP="patch"
          fi
          
          if [[ $VERSION_BUMP != "" ]]
          then
            NEW_VERSION=$(npm version $VERSION_BUMP)
            npm publish
            git push --tags
            gh release create $NEW_VERSION -t $NEW_VERSION -n "Release $NEW_VERSION"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
